version: '3.3'

services:
    # db:
    #     container_name: couture-mysql
    #     restart: always
    #     image: mysql/mysql-server:5.7.28
    #     expose:
    #         - "3306"
    #     networks:
    #         - backend
    #     environment:
    #         - MYSQL_DATABASE=${MYSQL_DATABASE}
    #         - MYSQL_USER=${MYSQL_USER}
    #         - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    #         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #         - MYSQL_ROOT_HOST=%
    #     volumes:
    #         - dbdata:/var/lib/mysql

    web:
        container_name: couture-mlflow
        restart: always
        build:
            context: https://github.com/coutureai/mlflow.git
        ports:
            - "5000:5000"
        networks:
            - frontend
            - backend
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
        # command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@couture-mysql:3306/${MYSQL_DATABASE} --default-artifact-root s3://mlflow --host 0.0.0.0        
        command: mlflow server --backend-store-uri sqlite:///store.db --default-artifact-root s3://mlflow --host 0.0.0.0        

    minio:
        container_name: couture-minio
        image: minio/minio
        ports:
            - "9000:9000"
        volumes:
            - ./minio/.minio/data:/export
            - ./minio/.minio/config:/root/.minio
        environment:
            - "MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}"
            - "MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}"
        entrypoint: sh
        command: -c 'mkdir -p /export/mlflow && /usr/bin/minio server /export'
        networks:
            - backend
            
networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    dbdata: